version: "3.9"

services:
  db:
    image: postgres:18-alpine
    container_name: qa_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    # ports:
    #   - "5432:5432"
    volumes:
      - qa_pg_data:/var/lib/postgresql/data
    networks:
      - qa_network

  api:
    build:
      context: .
    image: qa-api-server:latest
    container_name: qa_api_server
    depends_on:
      - db
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - qa_network


volumes:
  qa_pg_data:

networks:
  qa_network:
    driver: bridge
